### PR TITLE
homework

### PR DESCRIPTION
**Pull request by simonreddy2001**
waiting for feedback

### CODE REVIEW

**Comment by shanhaider23** [comment]
Good work! I can see only the Context part in homework but I am unable to see the fetching user from GitHub part of homework. I mean fetching Github API to find user

**Comment by simonreddy2001** [comment]
> Good work! I can see only the Context part in homework but I am unable to see the fetching user from GitHub part of homework. I mean fetching Github API to find user

you can see Git.js file .. https://github.com/simonreddy2001/hyf-homework/blob/react-week4/react/week4/github-user-search/src/Git.js

**Comment by shanhaider23** [comment]
Good work

**Comment by simonreddy2001** [comment]
> Good work

Thanks..

**Pull request merged**
